[profile.default]
src = "contracts"
out = "artifact/contracts"
libs = ["lib"]

[rpc_endpoints]
ethereum_sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
